/* AI 모델 도감 데이터
   fam: reg 숫자 예측 · cls 분류 · uns 비지도 · dl 딥러닝 · gen 생성형 · rl 강화 학습 · how 학습 방법
   tb : 2 = 교과서 본문에서 자세히(시험 범위 중심) · 1 = 교과서에 이름·읽을거리로 나옴 · 0 = 교과서 밖(넓혀 보기)
   p  : 교과서 쪽 · ow: 오렌지3 위젯 · nb: 실습 노트북 */
var MODELS = [
{ id:'linreg', fam:'reg', tb:2, p:'Ⅱ-04 · 104~107쪽 · Ⅳ 205~207쪽', name:'선형 회귀', en:'Linear Regression', icon:'📈',
  one:'점들 사이를 가장 잘 지나가는 <b>직선</b>을 찾아 숫자를 맞힌다.',
  like:'공부 시간과 점수를 점으로 찍고, 자를 대어 «평균적으로» 지나가는 선을 긋는 것.',
  how:['직선 y = a·x + b 를 아무렇게나 하나 긋는다.','모든 점에서 «실제값 − 예측값»(오차)을 재고 제곱해 평균 낸다(MSE).','MSE가 줄어드는 쪽으로 a(기울기)와 b(절편)를 조금씩 고친다 — 경사하강법.','더 줄어들지 않으면 멈춘다. 그 직선이 모델이다.'],
  key:'예측값 = a₁·x₁ + a₂·x₂ + … + b · 목표: MSE를 가장 작게',
  par:[['(설정값 거의 없음)','특성(x)을 무엇으로 고르느냐가 가장 중요']],
  pro:['빠르고 단순하다','기울기로 «x가 1 늘면 y가 a만큼» 설명할 수 있다','데이터가 적어도 안정적이다'],
  con:['관계가 곡선이면 잘 못 맞힌다','이상치 하나에 직선이 끌려간다','데이터 범위 밖(먼 미래)을 맞히면 크게 틀릴 수 있다'],
  use:['키로 몸무게 짐작','광고비로 매출 예측','교과서 — 도서관·공연장 수로 청년 인구, 기아 지수로 연도'],
  sk:"from sklearn.linear_model import LinearRegression\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\nprint(model.coef_, model.intercept_)   # 기울기 · 절편\nprint(model.score(X_test, y_test))     # R²",
  ow:'Linear Regression', nb:['02_model','07_ghi_hunger'] },

{ id:'poly', fam:'reg', tb:0, name:'다항 회귀', en:'Polynomial Regression', icon:'〰️',
  one:'x², x³ 같은 항을 더해 <b>곡선</b>으로 숫자를 맞힌다.',
  like:'자 대신 휘어지는 철사를 대어 점들을 따라가게 하는 것.',
  how:['원래 특성 x에서 x², x³ … 을 새 특성으로 만든다.','그 특성들로 선형 회귀를 한다 — 계산은 같고 모양만 곡선이 된다.','차수가 높을수록 더 구불구불해진다.'],
  key:'예측값 = a·x + b·x² + c·x³ + … + d',
  par:[['degree(차수)','2~3이면 충분한 경우가 많다. 너무 크면 점을 «외우는» 곡선(과적합)']],
  pro:['직선으로 안 되는 관계를 표현','선형 회귀와 같은 도구로 해결'],
  con:['차수가 크면 과적합 · 범위 밖에서 엉뚱한 값','특성이 많으면 항이 폭발적으로 늘어남'],
  use:['기온과 전력 사용량(너무 덥거나 추우면 모두 늘어남)','공 던진 높이의 포물선'],
  sk:"from sklearn.preprocessing import PolynomialFeatures\nfrom sklearn.pipeline import make_pipeline\nfrom sklearn.linear_model import LinearRegression\nmodel = make_pipeline(PolynomialFeatures(degree=2), LinearRegression())\nmodel.fit(X_train, y_train)",
  ow:'Polynomial Regression (애드온) · 또는 Feature Constructor + Linear Regression' },

{ id:'ridge', fam:'reg', tb:0, name:'릿지 · 라쏘 (규제)', en:'Ridge · Lasso', icon:'🧷',
  one:'선형 회귀가 가중치를 너무 크게 키우지 못하게 <b>벌점</b>을 준다 — 과적합 막기.',
  like:'시험 문제만 외우는 학생에게 «너무 한 문제에만 매달리면 감점» 규칙을 주는 것.',
  how:['선형 회귀의 목표(MSE)에 «가중치 크기»를 벌점으로 더한다.','릿지(L2)는 가중치를 골고루 작게, 라쏘(L1)는 쓸모없는 특성의 가중치를 0으로 만든다.','벌점 세기(alpha)는 사람이 정한다.'],
  key:'목표 = MSE + alpha × (가중치 크기)',
  par:[['alpha','클수록 단순한 모델. 0이면 그냥 선형 회귀']],
  pro:['특성이 많을 때 과적합을 줄인다','라쏘는 중요한 특성만 골라 준다'],
  con:['alpha를 잘 골라야 한다','특성 단위를 맞추는(정규화) 것이 좋다'],
  use:['특성이 수십 개인 집값 예측','유전자 데이터처럼 특성이 매우 많은 경우'],
  sk:"from sklearn.linear_model import Ridge, Lasso\nmodel = Ridge(alpha=1.0)    # 또는 Lasso(alpha=0.1)\nmodel.fit(X_train, y_train)",
  ow:'Linear Regression → Regularization: Ridge / Lasso', nb:['12_model_zoo'] },

{ id:'logreg', fam:'cls', tb:2, p:'Ⅱ-04 · 94쪽 · 부록 221~226쪽', name:'로지스틱 회귀', en:'Logistic Regression', icon:'🧮',
  one:'특성으로 점수를 매긴 뒤 <b>S자 곡선</b>에 넣어 0~1 <b>확률</b>로 바꾸고, 0.5를 넘으면 «예».',
  like:'거리별 슛 성공 기록을 보고 «이 거리에선 성공 확률 81%»라고 말해 주는 코치.',
  how:['특성마다 가중치를 곱해 더한 점수 z를 구한다.','z를 시그모이드(S자) 함수에 넣어 0~1 사이 확률로 만든다.','실제 정답과 확률의 차이(로그 손실)가 작아지도록 가중치를 고친다.','새 데이터는 확률 0.5를 기준으로 나눈다(기준은 바꿀 수 있다).'],
  key:'확률 = 1 / (1 + e^(−z)), z = a₁·x₁ + … + b',
  par:[['C (규제 세기의 역수)','작을수록 단순한 모델'],['class_weight','적은 쪽에 무게 — 불균형 데이터에서 «balanced»'],['max_iter','학습 반복 횟수 — 경고가 나면 늘리기']],
  pro:['확률을 준다 — 위험도처럼 해석 가능','가중치의 +/−로 방향을 설명','빠르고 기준선 모델로 좋다'],
  con:['경계가 곧은 선(면)이라 복잡한 모양은 못 나눔','이름은 회귀지만 분류 모델 — 헷갈리기 쉬움'],
  use:['스팸 / 정상','질병 위험 예측','교과서 — 슛 성공 확률, 약수터 물 적합/부적합'],
  sk:"from sklearn.linear_model import LogisticRegression\nmodel = LogisticRegression(max_iter=1000)\nmodel.fit(X_train, y_train)\nmodel.predict_proba(X_test)[:5]   # 집단마다 확률",
  ow:'Logistic Regression', nb:['09_water_logistic','12_model_zoo'] },

{ id:'knn', fam:'cls', tb:2, p:'Ⅱ-04 · 93쪽 · Ⅱ-05 108~112쪽 · 부록 213~218쪽', name:'k-최근접 이웃', en:'k-Nearest Neighbors (kNN)', icon:'🎯',
  one:'새 데이터와 <b>가장 가까운 k개</b>를 보고 다수결(예측이면 평균).',
  like:'전학 온 친구가 어느 동아리에 맞을지, 성향이 가장 비슷한 친구 셋이 어디 있는지 보고 정하는 것.',
  how:['학습 때는 데이터를 그냥 기억해 둔다(게으른 학습).','새 데이터가 오면 모든 데이터와의 거리를 잰다.','가까운 순서로 k개를 뽑는다.','그 k개의 다수결(예측이면 평균)이 답.'],
  key:'거리 = √((x₁−x₁′)² + (x₂−x₂′)² + …) · k는 사람이 정하는 하이퍼파라미터',
  par:[['n_neighbors (k)','작으면 우연에 휘둘림, 크면 다 비슷해짐. 두 집단이면 홀수'],['weights','distance — 가까운 이웃에 더 큰 표'],['metric','거리 재는 법(기본 유클리드)']],
  pro:['원리가 직관적','경계가 구불구불해도 됨','학습이 거의 즉시'],
  con:['단위가 다르면 큰 숫자가 거리를 독차지 → 정규화 필수','데이터가 많으면 예측이 느림','특성이 많으면 «가깝다»의 의미가 흐려짐'],
  use:['붓꽃 품종 분류','비슷한 상품 찾기','교과서 — 동물 보호소의 개/고양이, 스트레스 단계'],
  sk:"from sklearn.neighbors import KNeighborsClassifier\nfrom sklearn.pipeline import make_pipeline\nfrom sklearn.preprocessing import StandardScaler\nmodel = make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=5))\nmodel.fit(X_train, y_train)",
  ow:'kNN (+ Preprocess: Normalize)', nb:['02_model','08_stress_knn_tree','12_model_zoo'] },

{ id:'tree', fam:'cls', tb:2, p:'Ⅱ-04 · 96쪽 · 부록 213~218쪽', name:'의사결정트리', en:'Decision Tree', icon:'🌳',
  one:'데이터를 가장 깔끔하게 가르는 <b>예/아니요 질문</b>을 차례로 던져 나눈다.',
  like:'스무고개 — «동물인가요? → 다리가 넷인가요? → …».',
  how:['모든 특성 · 모든 기준값 중 «나눈 뒤 가장 순수해지는» 질문을 고른다(지니 불순도·엔트로피).','나뉜 두 무리 각각에서 다시 가장 좋은 질문을 고른다.','정한 깊이에 닿거나 더 나눌 게 없으면 멈춘다.','맨 끝(잎)의 다수결(예측이면 평균)이 답.'],
  key:'불순도(지니) = 1 − Σ(각 집단 비율)² — 0이면 한 집단뿐',
  par:[['max_depth','깊이 제한 — 가장 중요한 과적합 방지'],['min_samples_leaf','잎 하나에 최소 몇 개'],['criterion','gini / entropy']],
  pro:['판단 과정을 그림으로 설명 — 설명력 최고','숫자·범주 섞여도 되고 정규화 불필요','중요한 특성을 알려 줌'],
  con:['깊게 키우면 훈련 데이터를 외움(과적합)','데이터가 조금만 바뀌어도 나무 모양이 크게 바뀜','혼자서는 정확도가 높지 않은 편'],
  use:['대출 승인','진단 순서도','교과서 — 대출 심사 트리, 스트레스 단계'],
  sk:"from sklearn.tree import DecisionTreeClassifier, plot_tree\nmodel = DecisionTreeClassifier(max_depth=3, random_state=0)\nmodel.fit(X_train, y_train)\nplot_tree(model, feature_names=list(X.columns), filled=True)",
  ow:'Tree → Tree Viewer', nb:['08_stress_knn_tree','12_model_zoo'] },

{ id:'rf', fam:'cls', tb:0, name:'랜덤 포레스트', en:'Random Forest', icon:'🌲',
  one:'조금씩 다른 데이터로 <b>트리를 수백 그루</b> 키워 다수결 — «집단 지성».',
  like:'한 명의 심사위원 대신, 서로 다른 자료를 본 심사위원 100명의 투표.',
  how:['데이터를 중복 허용으로 무작위 추출해 트리마다 다른 훈련 세트를 만든다(배깅).','각 질문을 고를 때도 특성 일부만 무작위로 보게 한다.','트리들을 따로 키운 뒤 다수결(예측이면 평균).'],
  key:'여러 약한 모델의 오차는 서로 상쇄된다 — 앙상블',
  par:[['n_estimators','트리 수(100~500)'],['max_depth','트리 깊이'],['max_features','질문 고를 때 보는 특성 수']],
  pro:['정확도가 높고 과적합이 적다','설정을 크게 안 만져도 잘 된다','특성 중요도를 준다'],
  con:['나무 한 그루처럼 그려 설명하기 어렵다','모델이 크고 예측이 느릴 수 있다'],
  use:['신용 평가','질병 예측','표 형태 데이터 대회의 기본 강자'],
  sk:"from sklearn.ensemble import RandomForestClassifier\nmodel = RandomForestClassifier(n_estimators=200, random_state=0)\nmodel.fit(X_train, y_train)\nmodel.feature_importances_",
  ow:'Random Forest', nb:['12_model_zoo'] },

{ id:'gb', fam:'cls', tb:0, name:'그레이디언트 부스팅 (XGBoost · LightGBM)', en:'Gradient Boosting', icon:'🚀',
  one:'작은 트리를 <b>하나씩 차례로</b> 더하는데, 다음 트리는 앞 트리들이 <b>틀린 만큼</b>을 고친다.',
  like:'오답 노트 — 틀린 문제만 다시 공부하기를 수십 번 되풀이.',
  how:['작은 트리 하나로 예측한다.','실제값과의 차이(잔차)를 구한다.','그 잔차를 맞히는 새 트리를 만들어 조금(학습률)만 더한다.','정한 수만큼 반복한다.'],
  key:'예측 = 트리₁ + η·트리₂ + η·트리₃ + … (η: 학습률)',
  par:[['n_estimators','트리 수'],['learning_rate','한 번에 고치는 정도(0.01~0.3)'],['max_depth','보통 3~8로 작게']],
  pro:['표 데이터에서 가장 정확한 축','숫자·범주 섞인 데이터에 강함'],
  con:['설정값이 많고 과적합 위험','설명이 어렵고, 차례로 학습해 느릴 수 있음'],
  use:['캐글 대회 상위권 단골','추천·광고 클릭 예측'],
  sk:"from sklearn.ensemble import GradientBoostingClassifier\nmodel = GradientBoostingClassifier(learning_rate=0.1, n_estimators=100)\nmodel.fit(X_train, y_train)\n# 더 빠른 라이브러리: xgboost.XGBClassifier, lightgbm.LGBMClassifier",
  ow:'Gradient Boosting', nb:['12_model_zoo'] },

{ id:'svm', fam:'cls', tb:1, p:'Ⅱ-04 · 93쪽에 이름', name:'서포트 벡터 머신', en:'Support Vector Machine (SVM)', icon:'🛣️',
  one:'두 집단 사이에 <b>가장 넓은 빈 길(여백)</b>이 생기도록 경계를 긋는다.',
  like:'두 동네 사이에 도로를 낼 때, 양쪽 집들과 가장 멀리 떨어지게 길 한가운데를 잡는 것.',
  how:['두 집단을 나누는 경계 후보 중, 가장 가까운 점(서포트 벡터)과의 거리가 가장 먼 것을 찾는다.','곧은 선으로 안 나뉘면 커널로 데이터를 «높은 차원»으로 옮겨 나눈다.','조금 틀리는 것을 얼마나 허용할지(C) 정한다.'],
  key:'여백(margin)을 최대로 · 커널: linear / rbf',
  par:[['C','작으면 여백 넓게(조금 틀려도 됨), 크면 훈련 데이터에 딱 맞춤'],['kernel','linear / rbf'],['gamma','rbf의 휘는 정도']],
  pro:['특성이 많고 데이터가 중간 규모일 때 강함','커널로 곡선 경계도 가능'],
  con:['데이터가 많으면 느림','설정이 까다롭고 확률·설명이 약함','정규화 필수'],
  use:['손글씨 숫자 인식(딥러닝 이전)','문서 분류'],
  sk:"from sklearn.svm import SVC\nfrom sklearn.pipeline import make_pipeline\nfrom sklearn.preprocessing import StandardScaler\nmodel = make_pipeline(StandardScaler(), SVC(kernel='rbf', C=1.0))\nmodel.fit(X_train, y_train)",
  ow:'SVM', nb:['12_model_zoo'] },

{ id:'nb', fam:'cls', tb:1, p:'Ⅱ-04 · 93쪽에 이름', name:'나이브 베이즈', en:'Naive Bayes', icon:'📨',
  one:'특성마다 «이 집단이면 이런 값이 나올 확률»을 <b>곱해</b> 가장 그럴듯한 집단을 고른다.',
  like:'«무료», «당첨»이 들어간 메일이 스팸에서 얼마나 자주 나왔는지 세어 두었다가 새 메일에 적용.',
  how:['훈련 데이터에서 집단별로 각 특성 값이 나온 비율을 센다.','새 데이터의 특성 비율을 집단마다 모두 곱한다(베이즈 정리).','곱이 가장 큰 집단이 답.'],
  key:'P(집단|특성들) ∝ P(집단) × P(특성₁|집단) × P(특성₂|집단) × …',
  par:[['(설정값 거의 없음)','글자 데이터는 MultinomialNB, 숫자는 GaussianNB']],
  pro:['아주 빠르고 데이터가 적어도 버팀','글자(낱말) 분류에 강함'],
  con:['특성들이 서로 상관없다고 «순진하게» 가정','확률값 자체는 잘 안 맞는 편'],
  use:['스팸 메일 거르기','감성 분석의 기본 모델'],
  sk:"from sklearn.naive_bayes import GaussianNB\nmodel = GaussianNB()\nmodel.fit(X_train, y_train)",
  ow:'Naive Bayes', nb:['12_model_zoo'] },

{ id:'kmeans', fam:'uns', tb:2, p:'Ⅱ-04 · 97쪽', name:'k-평균 군집', en:'k-Means', icon:'🫧',
  one:'정답 없이 데이터를 <b>k개 무리</b>로 묶는다 — 중심을 옮겨 가며.',
  like:'운동장에 흩어진 학생들을 깃발 k개 주변으로 모이게 하고, 깃발을 무리 한가운데로 계속 옮기는 것.',
  how:['중심 k개를 아무 데나 찍는다.','각 데이터를 가장 가까운 중심에 배정한다.','중심을 자기 무리의 평균 위치로 옮긴다.','배정이 바뀌지 않을 때까지 2~3을 되풀이.'],
  key:'목표: 각 점과 자기 중심 사이 거리 제곱의 합을 최소로',
  par:[['n_clusters (k)','사람이 정함 — 엘보 방법·실루엣 점수로 고르기'],['n_init','처음 중심을 바꿔 여러 번 돌려 가장 좋은 것']],
  pro:['간단하고 빠르다','정답 열이 없어도 된다'],
  con:['k를 미리 정해야 함','동그란 무리가 아니면 잘 못 묶음','정규화 필요 · 무리의 «이름»은 사람이 붙임'],
  use:['고객을 소비 성향별로 나누기','교과서 — 점 12개를 두 무리로'],
  sk:"from sklearn.cluster import KMeans\nkm = KMeans(n_clusters=3, n_init=10, random_state=0)\nlabels = km.fit_predict(X_scaled)\nkm.cluster_centers_",
  ow:'k-Means (+ Silhouette Plot)', nb:['12_model_zoo'] },

{ id:'hier', fam:'uns', tb:0, name:'계층적 군집', en:'Hierarchical Clustering', icon:'🪜',
  one:'가장 가까운 것끼리 <b>두 개씩 합쳐 가며</b> 가계도(덴드로그램)를 만든다.',
  like:'반 친구들을 가장 친한 짝끼리 묶고, 짝끼리 다시 묶고 … 결국 반 전체가 하나가 되는 족보.',
  how:['처음엔 데이터 하나하나가 각자 한 무리.','가장 가까운 두 무리를 합친다.','하나가 될 때까지 반복하며 합친 순서를 나무 그림으로 남긴다.','원하는 높이에서 가지를 잘라 무리 수를 정한다.'],
  key:'무리 사이 거리 재는 법: 최단(single) · 최장(complete) · 평균 · 와드(ward)',
  par:[['linkage','ward가 보통 무난'],['자르는 높이 / n_clusters','덴드로그램을 보고 결정']],
  pro:['k를 미리 안 정해도 됨','덴드로그램으로 구조를 한눈에'],
  con:['데이터가 많으면 매우 느림','한 번 합치면 되돌릴 수 없음'],
  use:['생물 분류 계통도','비슷한 노래·문서 묶기'],
  sk:"from sklearn.cluster import AgglomerativeClustering\nlabels = AgglomerativeClustering(n_clusters=3, linkage='ward').fit_predict(X_scaled)",
  ow:'Distances → Hierarchical Clustering' },

{ id:'dbscan', fam:'uns', tb:0, name:'DBSCAN', en:'Density-Based Clustering', icon:'🌌',
  one:'점이 <b>빽빽하게 모인 곳</b>을 무리로, 동떨어진 점은 <b>잡음(이상치)</b>으로.',
  like:'밤하늘에서 별이 촘촘한 곳을 별자리로 묶고, 혼자 떨어진 별은 빼는 것.',
  how:['한 점의 반경 eps 안에 이웃이 min_samples개 이상이면 «중심점».','중심점끼리 이어지는 것들을 한 무리로 넓혀 간다.','어느 무리에도 못 들어간 점은 잡음.'],
  key:'밀도로 묶기 — 무리 수를 미리 안 정함',
  par:[['eps','이웃으로 볼 반경'],['min_samples','중심점이 되기 위한 최소 이웃 수']],
  pro:['구불구불한 모양의 무리도 찾음','이상치를 자동으로 골라냄'],
  con:['eps를 고르기 까다로움','밀도가 다른 무리가 섞이면 약함'],
  use:['GPS 위치로 자주 가는 장소 찾기','이상 거래 탐지'],
  sk:"from sklearn.cluster import DBSCAN\nlabels = DBSCAN(eps=0.5, min_samples=5).fit_predict(X_scaled)   # -1 = 잡음",
  ow:'DBSCAN' },

{ id:'pca', fam:'uns', tb:0, name:'주성분 분석 (차원 축소)', en:'PCA', icon:'🗜️',
  one:'특성 여러 개를 정보를 최대한 살린 채 <b>몇 개의 새 축</b>으로 줄인다.',
  like:'3차원 물체를 가장 많은 모습이 보이는 방향에서 찍은 2차원 사진.',
  how:['데이터가 가장 넓게 퍼진 방향을 첫 번째 축으로 잡는다.','그 축과 직각이면서 다음으로 넓게 퍼진 방향을 두 번째 축으로.','앞의 몇 축만 남기면 차원이 줄어든다.'],
  key:'설명된 분산 비율 — 축 몇 개로 정보의 몇 %를 담는가',
  par:[['n_components','남길 축 수(그림이면 2)']],
  pro:['특성이 많은 데이터를 2D 그림으로 보기','잡음 줄이기 · 다른 모델을 빠르게'],
  con:['새 축의 뜻을 말하기 어렵다','곧은 방향만 찾는다'],
  use:['설문 수십 문항을 두세 요인으로 요약','군집 결과를 평면에 그리기'],
  sk:"from sklearn.decomposition import PCA\npca = PCA(n_components=2)\nP = pca.fit_transform(X_scaled)\npca.explained_variance_ratio_",
  ow:'PCA', nb:['12_model_zoo'] },

{ id:'assoc', fam:'uns', tb:0, name:'연관 규칙 (장바구니 분석)', en:'Association Rules · Apriori', icon:'🛒',
  one:'«A를 산 사람은 B도 산다» 같은 <b>함께 일어나는 규칙</b>을 찾는다.',
  like:'편의점이 라면 옆에 김치를 두는 이유를 영수증 더미에서 찾아내는 것.',
  how:['자주 함께 나오는 묶음을 센다(지지도).','«A가 있을 때 B도 있을 비율»을 구한다(신뢰도).','우연보다 얼마나 자주인지 본다(향상도 > 1).'],
  key:'지지도 · 신뢰도 · 향상도',
  par:[['최소 지지도 · 최소 신뢰도','너무 낮으면 규칙이 쏟아지고, 높으면 다 사라짐']],
  pro:['결과가 «규칙» 문장이라 이해가 쉬움'],
  con:['상관일 뿐 원인은 아님','물건 종류가 많으면 계산량 폭발'],
  use:['진열 배치 · 묶음 할인','교과서 88쪽 추천 시스템과 이어짐'],
  sk:"# pip install mlxtend\nfrom mlxtend.frequent_patterns import apriori, association_rules\nfreq = apriori(basket_df, min_support=0.05, use_colnames=True)\nassociation_rules(freq, metric='lift', min_threshold=1.0)",
  ow:'Associate 애드온 · Frequent Itemsets → Association Rules' },

{ id:'cf', fam:'uns', tb:2, p:'Ⅱ-03 · 88쪽', name:'협업 필터링 (추천)', en:'Collaborative Filtering', icon:'🎬',
  one:'나와 <b>취향이 비슷한 사람</b>이 좋아한 것을 추천한다.',
  like:'«너랑 노래 취향 똑같은 친구가 요즘 이 노래 듣더라».',
  how:['사람 × 물건 표(구매·별점)를 만든다.','나와 기록이 비슷한 사람(또는 비슷하게 소비된 물건)을 찾는다.','그 사람이 좋아했지만 나는 아직 안 본 것을 추천한다.'],
  key:'유사도(코사인 · 상관) · 사용자 기반 / 아이템 기반',
  par:[['이웃 수','몇 명의 «비슷한 사람»을 볼지']],
  pro:['물건 내용을 몰라도 추천 가능'],
  con:['처음 온 사람·새 물건은 기록이 없어 추천이 어려움(콜드 스타트)','인기 있는 것만 더 추천되는 쏠림(필터 버블)'],
  use:['유튜브·넷플릭스·쇼핑몰 추천','교과서 — 라면·콜라 산 A와 B'],
  sk:"import pandas as pd\nR = df.pivot_table(index='사람', columns='물건', values='별점').fillna(0)\nsim = R.T.corr()   # 사람끼리 상관 — 가장 비슷한 사람의 별점을 참고",
  ow:'(오렌지3 기본 위젯 없음) Distances 로 유사도 보기' },

{ id:'perceptron', fam:'dl', tb:2, p:'Ⅱ-06 · 116~119쪽', name:'퍼셉트론', en:'Perceptron', icon:'⚡',
  one:'입력에 가중치를 곱해 더하고, 기준을 넘으면 1 — <b>신경 세포 하나</b>를 흉내 낸 모델.',
  like:'친구 셋의 의견을 각자 믿는 정도만큼 더해, 어느 점수를 넘으면 «가자!» 하는 결정.',
  how:['입력 x에 가중치 w를 곱해 모두 더하고 편향 b를 더한다.','활성화 함수(계단)로 0 또는 1을 낸다.','틀리면 가중치를 정답 쪽으로 조금 고친다.'],
  key:'출력 = 1 (w₁x₁ + w₂x₂ + b > 0 일 때) · 아니면 0',
  par:[['학습률','한 번에 고치는 정도']],
  pro:['신경망의 출발점 — 원리 이해에 최고','AND · OR 같은 곧은 선 문제는 해결'],
  con:['곧은 선으로 못 나누는 XOR은 풀 수 없음 → 층을 쌓아야 함'],
  use:['교과서 — AND · OR · XOR 진리표'],
  sk:"from sklearn.linear_model import Perceptron\nmodel = Perceptron()\nmodel.fit(X, y)",
  ow:'(Neural Network 위젯에서 은닉층 없이 비슷하게)' },

{ id:'mlp', fam:'dl', tb:2, p:'Ⅱ-06·07 · 118~130쪽', name:'심층 신경망 (다층 퍼셉트론)', en:'Deep Neural Network · MLP', icon:'🧠',
  one:'퍼셉트론을 <b>여러 층</b>으로 쌓아 복잡한 관계를 배운다 — 딥러닝의 기본형.',
  like:'한 사람이 못 푸는 문제를, 여러 단계로 나눠 맡는 팀(1층은 선, 2층은 모양, 3층은 판단 …).',
  how:['입력층 → 은닉층(여러 개) → 출력층으로 값을 흘려 보낸다(순전파).','은닉층마다 활성화 함수(ReLU 등)로 곡선적인 관계를 만든다.','출력과 정답의 차이(손실)를 구한다.','손실을 줄이도록 뒤에서부터 가중치를 고친다(오차 역전파 + 경사하강법). 이를 에포크만큼 반복.'],
  key:'층 = Dense(뉴런 수, 활성화) · 손실함수 · 옵티마이저(adam) · 에포크 · 배치',
  par:[['층 수 · 뉴런 수','클수록 표현력↑ · 과적합 위험↑'],['epochs · batch_size','반복 횟수 · 한 번에 보는 데이터 수'],['Dropout','학습 때 일부 뉴런을 쉬게 해 과적합 막기'],['출력층','두 갈래: 1개 + sigmoid / 여러 갈래: 종류 수 + softmax / 숫자: 1개 + 활성화 없음']],
  pro:['복잡한 관계를 스스로 찾음','데이터가 많을수록 강해짐'],
  con:['데이터와 계산이 많이 필요','왜 그렇게 답했는지 설명하기 어려움','설정값이 많음'],
  use:['교과서 — 독버섯 분류(정확도 0.99)','텐서플로 플레이그라운드(122쪽)'],
  sk:"from tensorflow import keras\nmodel = keras.Sequential([\n    keras.layers.Dense(64, activation='relu'),\n    keras.layers.Dense(8, activation='relu'),\n    keras.layers.Dense(1, activation='sigmoid')])\nmodel.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])\nmodel.fit(X_train, y_train, epochs=15, batch_size=256)",
  ow:'Neural Network', nb:['03_deeplearning','12_model_zoo'] },

{ id:'cnn', fam:'dl', tb:1, p:'Ⅱ-06 · 123쪽 읽을거리 · 부록 236쪽', name:'합성곱 신경망', en:'CNN', icon:'🖼️',
  one:'작은 <b>필터</b>로 사진을 훑어 가장자리·무늬 같은 특징을 찾고, 그 특징으로 분류한다.',
  like:'돋보기로 사진 구석구석을 훑으며 «여기 눈, 여기 귀»를 찾아 표시해 두는 것.',
  how:['합성곱층: 3×3 같은 작은 필터를 사진 위로 밀며 특징 지도(feature map)를 만든다.','풀링층: 특징 지도를 줄여 중요한 값만 남긴다(MaxPool).','합성곱·풀링을 반복하며 «선 → 모양 → 물체»로 점점 큰 특징을 찾는다.','마지막에 펼쳐(Flatten) 완전 연결층으로 분류한다.'],
  key:'Conv2D(필터 수, 크기) → MaxPooling2D → … → Flatten → Dense',
  par:[['필터 수 · 크기','보통 32·64개, 3×3'],['풀링 크기','2×2'],['데이터 늘리기','뒤집기·회전으로 사진 수를 늘려 과적합 막기']],
  pro:['사진 속 위치가 달라도 같은 특징을 찾음','같은 정확도에 가중치가 훨씬 적음'],
  con:['사진이 많이 필요(적으면 전이 학습)','GPU가 있으면 훨씬 빠름'],
  use:['얼굴 인식 · 자율 주행 카메라 · 의료 영상','교과서 — 흰쌀밥/흑미밥, 쓰레기 분류(티처블 머신 안쪽)'],
  sk:"from tensorflow.keras import layers, models\nmodel = models.Sequential([\n    layers.Input((150, 150, 3)),\n    layers.Conv2D(32, 3, activation='relu'), layers.MaxPooling2D(2),\n    layers.Conv2D(64, 3, activation='relu'), layers.MaxPooling2D(2),\n    layers.Flatten(), layers.Dense(64, activation='relu'),\n    layers.Dense(2, activation='softmax')])",
  ow:'Image Analytics 애드온 · Image Embedding(미리 학습된 CNN) → 분류 모델', nb:['10_food_image'] },

{ id:'rnn', fam:'dl', tb:1, p:'Ⅱ-06 · 123쪽 읽을거리', name:'순환 신경망 (RNN · LSTM)', en:'Recurrent Neural Network', icon:'🔁',
  one:'앞에서 본 것을 <b>기억</b>하며 순서대로 읽는다 — 문장·소리·시계열.',
  like:'책을 한 글자씩 읽으며 앞 내용을 머릿속에 들고 다니는 것.',
  how:['순서의 첫 값을 넣고 «기억(은닉 상태)»을 만든다.','다음 값을 넣을 때 앞의 기억도 함께 넣어 기억을 갱신한다.','끝까지 읽은 뒤(또는 매 단계) 출력한다.','LSTM·GRU는 «무엇을 잊고 무엇을 남길지» 문(gate)을 두어 긴 순서도 기억한다.'],
  key:'hₜ = f(xₜ, hₜ₋₁) — 지금 입력 + 이전 기억',
  par:[['은닉 크기','기억의 크기'],['순서 길이','한 번에 읽는 길이']],
  pro:['순서가 중요한 데이터에 맞음'],
  con:['긴 순서는 앞부분을 잊기 쉬움','한 단계씩 계산해 느림 → 요즘은 트랜스포머가 많이 대신함'],
  use:['주가·기온 예측','예전 번역기·음성 인식'],
  sk:"from tensorflow.keras import layers, models\nmodel = models.Sequential([\n    layers.Input((30, 1)),          # 30일치 기온\n    layers.LSTM(32),\n    layers.Dense(1)])               # 다음 날 기온",
  ow:'(기본 위젯 없음)' },

{ id:'transformer', fam:'gen', tb:0, name:'트랜스포머 (어텐션)', en:'Transformer', icon:'🔦',
  one:'문장 속 낱말들이 서로를 <b>얼마나 주목할지(어텐션)</b>를 계산해 한꺼번에 이해한다.',
  like:'«그것»이 무엇을 가리키는지 알기 위해 문장 전체에 형광펜을 칠해 보는 것.',
  how:['낱말(토큰)을 숫자 벡터로 바꾸고 위치 정보를 더한다.','셀프 어텐션: 각 낱말이 다른 모든 낱말과의 관련도를 계산해 섞는다.','이 층을 수십 겹 쌓는다.','다음 낱말 맞히기 같은 과제로 엄청난 양의 글을 학습한다.'],
  key:'Attention(Q, K, V) — 질문(Q)과 열쇠(K)가 맞을수록 값(V)을 더 가져온다',
  par:[['층 수 · 머리 수 · 매개변수 수','GPT류는 수십억~수조 개']],
  pro:['긴 문맥을 이해 · 병렬 계산으로 빠른 학습','글·그림·소리 모두에 쓰임'],
  con:['데이터·전기·계산 비용이 막대함','그럴듯한 거짓(환각)을 만들 수 있음'],
  use:['번역 · 검색 · 챗봇','이미지 인식(ViT)'],
  sk:"# pip install transformers\nfrom transformers import pipeline\nclf = pipeline('sentiment-analysis')\nclf('This rice is really delicious!')",
  ow:'Text Mining 애드온 · Document Embedding(미리 학습된 모델)' },

{ id:'llm', fam:'gen', tb:1, p:'Ⅱ-03 · 88쪽 · Ⅱ-06 120쪽 (챗GPT)', name:'대규모 언어 모델', en:'LLM · ChatGPT · Gemini · Claude', icon:'💬',
  one:'트랜스포머로 인터넷 규모의 글을 학습해 <b>다음 낱말을 맞히는</b> 모델 — 대화형 AI의 몸통.',
  like:'세상 책을 엄청나게 읽은 «문장 이어 쓰기» 선수에게, 사람이 «좋은 답» 고르는 법을 따로 가르친 것.',
  how:['사전 학습: 방대한 글에서 다음 낱말 맞히기를 반복한다.','지시 학습: 질문-좋은 답 예시로 대화하는 법을 배운다.','사람 피드백 강화 학습(RLHF): 사람이 더 낫다고 고른 답 쪽으로 다듬는다(교과서 85쪽 강화 학습).','답할 때는 낱말을 하나씩 확률로 골라 이어 쓴다.'],
  key:'P(다음 토큰 | 앞의 모든 토큰) · 사전 학습 + 미세 조정 + RLHF',
  par:[['temperature','클수록 다양하고 엉뚱, 작을수록 안정적'],['프롬프트','무엇을 어떻게 물을지가 결과를 바꿈']],
  pro:['글쓰기·요약·번역·코드 설명 등 거의 모든 언어 작업','예시 몇 개로 새 일을 해냄'],
  con:['사실이 아닌 것을 그럴듯하게 말함(환각) → 출처 확인 필수','학습 데이터의 편향을 따라함','내 답·판단을 대신 쓰게 하면 내 학습이 사라짐(우리 수업 «빨강»)'],
  use:['챗GPT · 제미나이 · 클로드','우리 수업 — AI 탐구 보조 · 소크라틱 AI · 티치백'],
  sk:"# 코랩에 내장된 AI나 API로 부를 수 있지만, 우리 수업에서는 «AI 탐구 교실» 안에서만 씁니다.",
  ow:'—' },

{ id:'gan', fam:'gen', tb:1, p:'Ⅱ-06 · 123쪽 읽을거리', name:'생성적 적대 신경망', en:'GAN', icon:'🎭',
  one:'<b>위조범(생성자)</b>과 <b>감정사(판별자)</b>가 서로 겨루며 진짜 같은 데이터를 만든다.',
  like:'위조지폐범과 경찰이 겨룰수록 위조 실력도 감별 실력도 늘어 가는 것.',
  how:['생성자가 무작위 잡음에서 가짜 그림을 만든다.','판별자는 진짜와 가짜를 가린다.','판별자는 더 잘 가리도록, 생성자는 판별자를 속이도록 번갈아 학습한다.','균형에 이르면 생성자가 진짜 같은 그림을 만든다.'],
  key:'생성자 G vs 판별자 D — 서로의 손실이 반대 방향',
  par:[['잡음 크기 · 두 신경망 구조','학습이 불안정해 조절이 까다로움']],
  pro:['진짜 같은 얼굴·그림 생성','데이터 늘리기에 활용'],
  con:['학습이 불안정 · 한 종류만 만드는 문제(모드 붕괴)','딥페이크 같은 악용 위험'],
  use:['가상 인물 얼굴 생성','흑백 사진 채색 · 해상도 높이기'],
  sk:"# 구조만 — 생성자와 판별자 두 신경망을 번갈아 학습\nG = keras.Sequential([...])   # 잡음 → 그림\nD = keras.Sequential([...])   # 그림 → 진짜일 확률",
  ow:'—' },

{ id:'diffusion', fam:'gen', tb:0, name:'확산 모델', en:'Diffusion Model', icon:'🌫️',
  one:'그림에 잡음을 조금씩 섞는 과정을 <b>거꾸로</b> 배워, 잡음에서 그림을 만들어 낸다.',
  like:'물에 퍼진 잉크 방울을 영상으로 거꾸로 돌려 다시 한 방울로 모으는 것.',
  how:['진짜 그림에 잡음을 단계별로 더해 완전한 잡음으로 만든다.','각 단계에서 «더해진 잡음»을 맞히도록 신경망을 학습한다.','만들 때는 완전한 잡음에서 시작해 잡음을 조금씩 걷어 낸다.','글(프롬프트)을 조건으로 주면 원하는 그림 쪽으로 걷어 낸다.'],
  key:'노이즈 추가(정방향) ↔ 노이즈 제거(역방향) 수십~수백 단계',
  par:[['단계 수 · 안내 세기(guidance)','많을수록 정교하지만 느림']],
  pro:['GAN보다 안정적이고 다양한 고품질 그림'],
  con:['만드는 데 여러 단계라 느림','저작권·초상권·가짜 이미지 문제'],
  use:['글로 그림 그리기(이미지 생성 AI)','동영상·음악 생성'],
  sk:"# pip install diffusers  (GPU 필요)\nfrom diffusers import StableDiffusionPipeline",
  ow:'—' },

{ id:'rl', fam:'rl', tb:2, p:'Ⅱ-03 · 85~91쪽', name:'강화 학습 (Q-러닝 · DQN)', en:'Reinforcement Learning', icon:'🕹️',
  one:'행동하고 <b>보상</b>을 받으며, 점수가 가장 커지는 <b>전략</b>을 스스로 익힌다.',
  like:'게임을 수천 판 하면서 «어디서 무엇을 하면 점수가 나는지» 몸으로 깨치는 것.',
  how:['에이전트가 상태를 보고 행동을 고른다.','환경이 보상(+/−)과 다음 상태를 준다.','«이 상태에서 이 행동의 가치(Q)»를 보상으로 조금씩 고친다.','새 길 시도(탐험)와 아는 길(이용)의 균형을 잡으며 반복한다.'],
  key:'Q(상태, 행동) ← Q + 학습률 × (보상 + 할인율 × 다음 최대 Q − Q)',
  par:[['학습률 · 할인율','미래 보상을 얼마나 중요하게'],['ε (탐험 비율)','처음엔 크게, 점점 작게']],
  pro:['정답 데이터 없이 시행착오로 배움','사람도 못 찾은 전략을 찾기도'],
  con:['시행착오가 엄청나게 많이 필요','보상을 잘못 설계하면 엉뚱한 «꼼수»를 배움'],
  use:['알파고 · 로봇 걷기 · 자율 주행','교과서 — DQN 블록 깨기, 챗GPT의 RLHF'],
  sk:"import numpy as np\nQ = np.zeros((상태수, 행동수))\na = np.argmax(Q[s]) if np.random.rand() > eps else np.random.randint(행동수)\nQ[s, a] += lr * (r + gamma * Q[s2].max() - Q[s, a])",
  ow:'—' },

{ id:'transfer', fam:'how', tb:1, p:'Ⅱ-07 · 131~135쪽(티처블 머신)', name:'전이 학습', en:'Transfer Learning', icon:'🎒',
  one:'이미 수많은 데이터로 학습한 모델의 «눈»을 빌려, 내 적은 데이터로 <b>마지막 부분만</b> 다시 가르친다.',
  like:'영어를 잘하는 사람이 프랑스어를 처음부터가 아니라 «비슷한 부분은 그대로 쓰며» 빨리 배우는 것.',
  how:['큰 데이터(수백만 장 사진)로 미리 학습된 CNN을 가져온다.','앞쪽 층(특징 찾기)은 그대로 얼린다.','마지막 분류층만 내 클래스(플라스틱·유리·종이)에 맞게 새로 붙여 학습한다.'],
  key:'사전 학습 모델(MobileNet 등) + 새 출력층',
  par:[['얼릴 층 수','데이터가 적을수록 많이 얼린다'],['에포크 · 학습률','티처블 머신 «고급» 칸']],
  pro:['사진 수십 장으로도 쓸 만한 정확도','학습이 빠름'],
  con:['원래 모델이 본 적 없는 종류(의료 영상 등)는 효과가 줄어듦','원래 모델의 편향도 함께 물려받음'],
  use:['티처블 머신 이미지·소리·자세 프로젝트','교과서 — 쓰레기 분류, 새 소리 분류'],
  sk:"from tensorflow import keras\nbase = keras.applications.MobileNetV2(input_shape=(224, 224, 3), include_top=False, pooling='avg')\nbase.trainable = False\nmodel = keras.Sequential([base, keras.layers.Dense(3, activation='softmax')])",
  ow:'Image Embedding → Logistic Regression (같은 원리)', nb:['11_teachable_machine'] }
];
